filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log # Path to Docker JSON log files on the host
  # processors: # Uncomment and configure if you need to add Docker metadata explicitly
  #  - add_docker_metadata: ~

  # Optional: Filter to collect logs only from your Flask application container
  # This assumes your Flask app container will be named 'yt-sentiment-app' (as per Jenkinsfile)
  # condition:
  #   contains:
  #     container.name: "yt-sentiment-app"

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# Output to Logstash
output.logstash:
  hosts: ["${LOGSTASH_HOST:logstash:5044}"] # Connects to Logstash service on port 5044

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~ # Enrich logs with Docker metadata (like container name, image, etc.)
  - add_host_metadata: ~   # Enrich logs with host metadata

# Optional: Filebeat logging settings
# logging.level: info
# logging.to_files: true
# logging.files:
#   path: /var/log/filebeat
#   name: filebeat
#   keepfiles: 7
#   permissions: 0644