apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: yt-comment-analysis
  endpoints:
  - port: web
    path: /metrics
    interval: 15s
    scheme: http