---
- name: Ensure kubectl is installed
  apt:
    name: kubectl
    state: present
    update_cache: yes

- name: Create deployment manifest
  template:
    src: deployment.j2
    dest: "/tmp/{{ app_name }}-deployment.yaml"

- name: Create service manifest
  template:
    src: service.j2
    dest: "/tmp/{{ app_name }}-service.yaml"

- name: Deploy to Kubernetes
  command: "kubectl apply -f /tmp/{{ app_name }}-{{ item }}.yaml"
  loop:
    - deployment
    - service
  register: deploy_result
  changed_when: "'created' in deploy_result.stdout or 'configured' in deploy_result.stdout"

- name: Verify deployment
  command: "kubectl rollout status deployment/{{ app_name }}"
  register: rollout
  retries: 10
  delay: 10
  until: rollout.rc == 0