# elk-stack-values.yaml
elasticsearch:
  enabled: true
  replicas: 1  # Single-node cluster
  minimumMasterNodes: 1
  resources:
    requests:
      cpu: "500m"  # Half CPU core
      memory: "1Gi"  # Absolute minimum
    limits:
      memory: "2Gi"  # Prevent OOM kills
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "standard"
    resources:
      requests:
        storage: "5Gi"  # Reduced disk size

kibana:
  enabled: true
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
  service:
    type: NodePort

# Disable resource-heavy features
esConfig:
  elasticsearch.yml: |
    xpack.ml.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false