# elk-stack-values.yaml
elasticsearch:
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      memory: "2Gi"
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "standard"
    resources:
      requests:
        storage: "5Gi"

kibana:
  enabled: true
  service:
    type: NodePort  # Or LoadBalancer for cloud providers

logstash:
  enabled: false  # Disable if not needed