# elk-stack-values.yaml
elasticsearch:
  resources:
    requests:
      cpu: "1000m"
      memory: "4Gi"
    limits:
      memory: "8Gi"
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "standard"
    resources:
      requests:
        storage: "10Gi"

kibana:
  enabled: true
  service:
    type: NodePort  # Or LoadBalancer for cloud providers

logstash:
  enabled: false  # Disable if not needed