filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.enabled: false