apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-comment-deployment
  labels:
    app: yt-comment-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-comment-analysis
  template:
    metadata:
      labels:
          app: yt-comment-analysis
    spec:
      containers:
        - name: yt-comment-container
          image: "{{ image_name }}" # This will be replaced by the image name from Jenkins
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
