apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-comment-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yt-comment-analysis
  template:
    metadata:
      labels:
        app: yt-comment-analysis
    spec:
      containers:
      - name: app
        image: paranoid02/yt-comment-sentiment-analysis:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: app-secrets
