---
apiVersion: v1
kind: Service
metadata:
  name: yt-comment-service
spec:
  type: NodePort
  selector:
    app: yt-comment-analysis
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
  selector:
    app: yt-comment-analysis


#---
# apiVersion: v1
# kind: Service
# metadata:
#   name: yt-comment-service
#   namespace: default
# spec:
#   selector:
#     app: yt-comment-analysis
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer