---
apiVersion: v1
kind: Service
metadata:
  name: yt-comment-service
spec:
  selector:
    app: yt-comment-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer