artifact_location: /Users/akshay/Developer/Code/Machine Learning/yt-comment-analysis/yt-comment-sentiment-analysis/ec2-13-60-22-71.eu-north-1.compute.amazonaws.com5000/0
creation_time: 1744910757203
experiment_id: '0'
last_update_time: 1744910757203
lifecycle_stage: active
name: Default
