---
- hosts: localhost
  connection: local
  vars:
    image_name: "{{ image_name }}"
    k8s_namespace: "default"
  vars_files:
    - secret_vars.yml

  pre_tasks:
    - name: Debug variables
      debug:
        msg: "Using image: {{ image_name }} in namespace: {{ k8s_namespace }}"
      
    - name: Check minikube status
      command: minikube status
      register: minikube_status
      ignore_errors: yes
      changed_when: false
      
    - name: Start minikube if not running
      command: minikube start --driver=docker
      when: minikube_status.rc != 0
      
  roles:
    - role: kubernetes_secrets

  tasks:
    - name: Debug variables
      debug:
        msg: "Deploying image: {{ image_name }} to namespace: {{ k8s_namespace }}"

    - name: Create processed deployment file
      template:
        src: templates/deployment.yaml.j2
        dest: ../kubernetes/deployment-processed.yaml
      
    - name: Apply Kubernetes resources
      kubernetes.core.k8s:
        state: present
        src: "../kubernetes/{{ item }}"
        namespace: "{{ k8s_namespace }}"
      loop:
        - deployment-processed.yaml
        - service.yaml
      register: apply_result
      retries: 3
      delay: 10
      
    - name: Verify deployment rollout
      command: kubectl rollout status deployment/yt-comment-deployment -n {{ k8s_namespace }} --timeout=180s
      register: rollout
      until: rollout.rc == 0
      retries: 5
      delay: 15
      ignore_errors: yes

    - name: Check pods status
      command: kubectl get pods -l app=yt-comment-analysis -n {{ k8s_namespace }} -o wide
      register: pods
      changed_when: false

    - name: Debug pod issues if any
      debug:
        msg: "Pod status: {{ pods.stdout }}"
      when: rollout.rc != 0