---
- hosts: localhost
  connection: local
  vars:
    image_name: "{{ image_name }}"
    minikube_driver: "docker"
  tasks:
    - name: Check if Minikube is running
      command: minikube status
      register: minikube_status
      ignore_errors: yes
      changed_when: false

    - name: Delete existing Minikube cluster if driver mismatch
      command: minikube delete
      when: 
        - "'Running' not in minikube_status.stdout"
        - "'docker' not in minikube_status.stdout"  # Adjust based on your actual driver
      async: 60
      poll: 5

    - name: Start Minikube with correct driver
      command: minikube start --driver={{ minikube_driver }}
      when: "'Running' not in minikube_status.stdout"
      async: 300
      poll: 10
      register: minikube_start
      until: minikube_start.finished
      retries: 3

    - name: Verify Minikube is ready
      command: minikube status
      register: minikube_ready
      until: "'Running' in minikube_ready.stdout"
      retries: 10
      delay: 10

    - name: Enable registry addon
      command: minikube addons enable registry
      register: addon_result
      changed_when: "'was successfully enabled' in addon_result.stdout"

    - name: Set docker env to minikube
      shell: |
        eval $(minikube -p minikube docker-env)
        docker info
      args:
        executable: /bin/bash

    - name: Apply Kubernetes deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'kubernetes/deployment.yaml') | from_yaml }}"

    - name: Apply Kubernetes service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'kubernetes/service.yaml') | from_yaml }}"